import type { Metadata } from "next";
import ClientLayout from "./layouts/ClientLayout";
import "antd/dist/reset.css";
import "./globals.css";
import { Poppins } from "next/font/google";
import { startLowStockNotifier } from "@/jobs/lowStockNotifier";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "StackPro",
  description: "Generated by create next app",
};

startLowStockNotifier();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={poppins.className}>
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
