import type { Metadata } from "next";
import ClientLayout from "./layouts/ClientLayout";
import "antd/dist/reset.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "StackPro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
